### ISSUE TITLE
DSGVO Problem

### ISSUE THREAD

**Issue by LvckyAPI** [StrandedDevcoon/Figma_Clone#8]
## Story
An folgenden Stellen, werden wahrscheinlich externe dienste lokal geladen.  
Um eine teure Abmanhung zu verhindern, muss ein anderer Weg gefunden werden.

- https://github.com/StrandedDevcoon/Figma_Clone/blob/main/components/comments/PinnedComposer.tsx#L15
- https://github.com/StrandedDevcoon/Figma_Clone/blob/main/components/comments/PinnedThread.tsx#L45

## Todo:
- [ ] prüfen ob wirklich eine Verbindung aufgebaut wird
- [ ] eine Möglichkeit finden, diese Dinge anders einzubinden
- [ ] Implementieren einer Lösung
